// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unhgjgrgsciuozgxyytf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuaGdqZ3Jnc2NpdW96Z3h5eXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDA2OTYsImV4cCI6MjA3MzY3NjY5Nn0.jWxQ-56WNNp39jJJ9m8LZGLyJlf3dx4wlMF1syJOVro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});